### PR TITLE
Various fixes to PyAFS

### PR DESCRIPTION
**Pull request by dehnert**
I've been working on using PyAFS with a project of mine. Here's one documentation fix, and two changes to make it build on scripts these days (one due to new Cython, and one due to Fedora not being Debian, I think).

### CODE REVIEW

**Comment by dehnert** [comment]
Oh, also, if you want some Fedora packaging, that'll probably exist in the Scripts repo soonish, and I can send it along when it does if you want.

**Comment by ebroder** [comment]
LGTM, but could you please sign off on your patches before I merge?

**Comment by dehnert** [comment]
Uh, sure. Is this what you wanted?

(License is GPLv2, right? I don't actually see a copyright statement on master, but debian implies that both content and packaging are GPL'd.)

**Comment by ebroder** [comment]
Yeah, it's GPLv2. Documented in the setup.py file; there should probably be a COPYING too, though. I'll open an issue for that.

**Pull request merged**
